### ISSUE TITLE
Takedown Request

### ISSUE THREAD

**Issue by webspec** [gauravkarki78/grepsr-assignment#1]
Hello,

We're asking that you please remove [this file](https://github.com/gauravkarki78/grepsr-assignment/blob/main/Week-3/Dealer-Detail-Extraction/response.html) from your repository in its entirety (including commits, local copies, etc.). This file contains a private API key.

If you have questions, feel free to reach out to security@webspec.com

Thank you

**Comment by gauravkarki78** [comment]
c07920da8f6efecb2d7adfeb4ac70c8f55b0e2ff solves issue #1

**Comment by webspec** [comment]
Thank you @gauravkarki78 - We appreciate the quick response!
